;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	keyboard-escape-quit
	))

(setq mc/cmds-to-run-once
      '(
	cljr-helm
	hydra-cljr-code-menu/cljr-introduce-let
	hydra-cljr-code-menu/cljr-move-to-let
	hydra-cljr-code-menu/cljr-unwind-all
	hydra-cljr-code-menu/nil
	hydra-cljr-help-menu/hydra-cljr-code-menu/body-and-exit
	))
